### ISSUE TITLE
SMS Marketing NOT WORKING

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#34]
We've just sent 1500 sms from Dough and they haven't delivered. Furthermore we tried an email and it just went with the subject line special offer with no content... so now we just look like idiots who don't know what we're doing.

**Comment by WanderingDaniel** [comment]
So having looked into this 

- The SMS messages did not send because they would have failed gateway requirements. Have resolved this so it alerts
- The email sent with no body as no body was seemingly added, but I think a result of bad explanations on the UI 

I've updated the UI to resolve both issues.
